# render.yaml

services:
  - type: web
    name: anton-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn anton_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
